create table units (id VARCHAR PRIMARY KEY, code VARCHAR, system VARCHAR, display VARCHAR)
insert into units values ("1", "[degF]", "http://unitsofmeasure.org", "[degF]")
insert into units values ("2", "/min", "http://unitsofmeasure.org", "/min")
insert into units values ("3", "mm[Hg]", "http://unitsofmeasure.org", "mm[Hg]")
insert into units values ("4", "kg", "http://unitsofmeasure.org", "kg")
insert into units values ("5", "g/dL", "http://unitsofmeasure.org", "g/dL")
insert into units values ("6", "mg/dL", "http://unitsofmeasure.org", "mg/dL")
insert into units values ("7", "mg/L", "http://unitsofmeasure.org", "mg/L")
insert into units values ("8", "g/L", "http://unitsofmeasure.org", "g/L")
insert into units values ("9", "mmol/L", "http://unitsofmeasure.org", "mmol/L")
insert into units values ("10", "cells/mL", "http://unitsofmeasure.org", "cells/mL")
insert into units values ("11", "cm", "http://unitsofmeasure.org", "cm")